spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dep
    username: postgres
    password: root
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL81Dialect
    show-sql: false
  springdoc:
    pathsToMatch: /person/**
    swagger-ui:
      user-toot-path: true