# configuração do token
security:
  jwt:
    token:
#      chave secreta
      secret-key: 53cr37
#      expiração do token em mile segundos
      expire-lenght: 3600000

#      configuração do banco de dados
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dep
    username: postgres
    password: root
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL81Dialect
    show-sql: false
  springdoc:
    pathsToMatch: /person/**
    swagger-ui:
      user-toot-path: true